# Generated by Django 5.2.5 on 2025-08-25 18:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=200, unique=True)),
                ('pershkrimi', models.TextField()),
                ('data_krijimit', models.DateTimeField(auto_now_add=True)),
                ('strategjia', models.TextField(help_text='Përshkrimi i strategjisë së investimit')),
            ],
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri_dokumentit', models.CharField(max_length=255)),
                ('lloji', models.CharField(choices=[('PROSPEKT', 'Prospekti i Fondit'), ('KIID', 'Dokumenti me Informacionin Kyç'), ('RAPORT_VJETOR', 'Raport Vjetor'), ('RAPORT_GJASHTEMUJOR', 'Raport Gjashtëmujor')], max_length=25)),
                ('skedari', models.FileField(upload_to='dokumente_fondi/')),
                ('data_publikimit', models.DateField()),
                ('fondi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumentet', to='portali_investitorit.fond')),
            ],
        ),
        migrations.CreateModel(
            name='AsetPortofoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simboli', models.CharField(help_text="P.sh. 'EUR/USD', 'GOLD', 'AAPL'", max_length=20)),
                ('sasia', models.DecimalField(decimal_places=4, max_digits=19)),
                ('vlera_mesatare_blerjes', models.DecimalField(decimal_places=4, max_digits=19)),
                ('data_e_fundit_perditesimit', models.DateTimeField(auto_now=True)),
                ('fondi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asetet', to='portali_investitorit.fond')),
            ],
        ),
        migrations.CreateModel(
            name='Investim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sasia_kuotave', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('vlera_totale_investuar', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('fondi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portali_investitorit.fond')),
                ('investitori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lloji', models.CharField(choices=[('DEPOZITE', 'Depozitë'), ('TERHEQJE', 'Tërheqje'), ('BLERJE', 'Blerje Kuotash'), ('SHITJE', 'Shitje Kuotash')], max_length=10)),
                ('shuma', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sasia_kuotave', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('cmimi_per_kuote', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('data_transaksionit', models.DateTimeField(auto_now_add=True)),
                ('statusi', models.CharField(default='E Përfunduar', max_length=20)),
                ('investimi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksionet', to='portali_investitorit.investim')),
            ],
        ),
        migrations.CreateModel(
            name='VleraNetoeAsetit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('vlera_per_kuote', models.DecimalField(decimal_places=4, max_digits=19)),
                ('fondi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_nav', to='portali_investitorit.fond')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
