# Generated by Django 5.2.5 on 2025-08-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portali_investitorit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='vlera_aktuale_e_kuotes',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Vlera aktuale e tregut për një kuotë të vetme', max_digits=19),
        ),
    ]
